### ISSUE TITLE
Project Config Files

### ISSUE THREAD

**Issue by SunriseLong** [tagr-dev/tagr#9]
Engineers should be able to add `tagr` into their projects and run the library out of the box with minimal configurations. Given the nature of how experiments are run, and the parameter heavy of calls to cloud skd's, commonly passed params like bucket and experiment name should be abstracted. 

I propose implementing two config files that tagr should expect in any project. 

**tagr-project.yml**
```
name: "mejuri-predictor"                  (bucket name)
experiment: "random-forest-with-holdout"      (experiment name)
version: "0.2"                                                        (optional for name spacing)
profile: "mejuri-aws-ds"                                      (name of profile to use in `profiles.yml`)
```

**tagr-profile.yml**
```
mejuri-aws-ds:
    aws:
        aws_access_key_id:
        aws_secret_access_key:
    local:
       target_dir:
```

with these two files provided, user will only need to pass cloud provider credentials, bucket and experiment once. We can extend these files in the future to specify the version of features of tagr to run
